#!/usr/bin/env ruby

require 'fileutils'

PLATFORM_DARWIN = "Darwin"
PLATFORM_LINUX = "Linux"
PLATFORM = `uname`.chomp

DEPENDENCIES = [ "git", "vim", "neovim", "silversearcher-ag", "zsh" ]
GEMS = ["homesick"]

def system_or_exit1(*args)
  unless system(*args)
    puts "ERROR: Command failed. Aborting."
    exit 1
  end
  true
end

def has_cmd?(cmd)
  system_or_exit1("which #{cmd}", STDOUT => '/dev/null') == true
end

def install(cmd)
  if PLATFORM == PLATFORM_LINUX
    system_or_exit1("sudo apt-get -y install #{cmd}")
  elsif PLATFORM == PLATFORM_DARWIN
    system_or_exit1("brew install #{cmd}")
  else
    raise "Unsupported Platform: #{PLATFORM}"
  end
end

def install_gem(_gem)
  system_or_exit1("sudo gem install #{_gem}")
end

def move_defaults
  if File.exist?("#{ENV['HOME']}/.zshrc")
    puts "WARN: Moving #{ENV['HOME']}/.zshrc to #{ENV['HOME']}/.zshrc.default"
    puts "      This file is load by the dotfile .zshrc"
    FileUtils.mv("#{ENV['HOME']}/.zshrc", "#{ENV['HOME']}/.zshrc.default")
  end

  if File.exist?("#{ENV['HOME']}/.gitconfig")
    puts "WARN: Moving #{ENV['HOME']}/.gitconfig to #{ENV['HOME']}/.gitconfig.default"
    puts "      This file is load by the dotfile .gitconfig"
    FileUtils.mv("#{ENV['HOME']}/.gitconfig", "#{ENV['HOME']}/.gitconfig.default")
  end
end

def install_fzf
  system_or_exit1("git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf")
  system_or_exit1("~/.fzf/install")
end

def install_vundle
  system_or_exit1("git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle")
end

puts "1. Installing dependencies"
DEPENDENCIES.each do |app|
  unless has_cmd?(app)
    puts "Installing: #{app}"
    install(app)
  end
end

puts "2. Installing gems"
GEMS.each do |app|
  unless has_cmd?(app)
    puts "Installing Ruby Gem: #{app}"
    install_gem(app)
  end
end

puts "3. Installing fzf"
install_fzf

puts "4. Moving existing defaults"
move_defaults

puts "5. Cloning dotfiles"
system_or_exit1("mkdir -p $HOME/.homesick/repos")
system_or_exit1("git clone --recursive https://github.com/hkdsun/dotfiles.public $HOME/.homesick/repos/dotfiles.public")

puts "6. Linking dotfiles"
system_or_exit1("homsick link dotfiles.public")

puts "7. Installing VIM Plugins"
install_vundle
system_or_exit1('nvim --headless --noplugin -u $HOME/.vim/vundles.vim +PluginInstall +qall')
