#!/usr/bin/env ruby

PLATFORM_DARWIN = "Darwin"
PLATFORM_LINUX = "Linux"
PLATFORM = `uname`.chomp

DEPENDENCIES = [ "git", "vim" ]

GEMS = ["homesick"]


def has_cmd?(cmd)
  system("which #{cmd}", STDOUT => '/dev/null') == true
end

def install(cmd)
  if PLATFORM == PLATFORM_LINUX
    system("apt-get -y install #{cmd}")
  elsif PLATFORM == PLATFORM_DARWIN
    system("brew install #{cmd}")
  else
    raise "Unsupported Platform: #{PLATFORM}"
  end
end

def install_gem(_gem)
  system("gem install #{_gem}")
end

puts "1. Installing dependencies"
DEPENDENCIES.each do |app|
  unless has_cmd?(app)
    puts "Installing: #{app}"
    install(app)
  end
end

puts "2. Installing gems"
GEMS.each do |app|
  unless has_cmd?(app)
    puts "Installing Ruby Gem: #{app}"
    install_gem(app)
  end
end

if File.exist?("#{ENV['HOME']}/.zshrc")
  puts "WARN: Moving #{ENV['HOME']}/.zshrc to #{ENV['HOME']}/.zshrc.default"
  puts "      This file is load by the dotfile .zshrc"
  File.mv("#{ENV['HOME']}/.zshrc", "#{ENV['HOME']}/.zshrc.default")
end

if File.exist?("#{ENV['HOME']}/.gitconfig")
  puts "WARN: Moving #{ENV['HOME']}/.gitconfig to #{ENV['HOME']}/.gitconfig.default"
  puts "      This file is load by the dotfile .gitconfig"
  File.mv("#{ENV['HOME']}/.gitconfig", "#{ENV['HOME']}/.gitconfig.default")
end


puts "3. Cloning dotfiles"
system("mkdir -p $HOME/.homesick/repos")
system("git clone --recursive https://github.com/hkdsun/dotfiles.public $HOME/.homesick/repos/dotfiles.public")
puts "4. Linking dotfiles"
system("homsick link dotfiles.public")
